import { User } from './types'

export const data = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@company.com',
    roleTitle: 'Software Engineer',
    status: 'Approved',
    approved: 'Ken',
    createdDate: '2024/03/25',
    lastLogin: '2024/03/30 9:15',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@company.com',
    roleTitle: 'Marketing Manager',
    status: 'Pending',
    approved: 'Jen',
    createdDate: '2024/03/28',
    lastLogin: '2024/03/28 9:15',
  },
  {
    id: '3',
    name: 'Chantel Pedro',
    email: 'chantel.pedro@company.com',
    roleTitle: 'Sales Representative',
    status: 'Approved',
    approved: 'Kim',
    createdDate: '2024/03/30',
    lastLogin: '2024/03/30 10:45',
  },

  {
    id: '4',
    name: 'Lizabeth Andrei',
    email: 'lizabeth.andrei@company.com',
    roleTitle: 'Human Resources',
    status: 'Active',
    approved: 'Kim',
    createdDate: '2024/03/15',
    lastLogin: '2024/04/01 9:15',
  },
  {
    id: '5',
    name: 'Olivia Jones',
    email: 'olivia.jones@company.com',
    roleTitle: 'Human Resources',
    status: 'Active',
    approved: 'Ken',
    createdDate: '2024/03/15',
    lastLogin: '2024/04/01 14:39',
  },

  {
    id: '6',
    name: 'Jenna Verde',
    email: 'jenna.verde@company.com',
    roleTitle: 'Human Resources',
    status: 'Pending',
    approved: 'Kim',
    createdDate: '2024/03/15',
    lastLogin: '2024/04/01 8:49',
  },

  {
    id: '7',
    name: 'Colt Hardings',
    email: 'colt.hardings@company.com',
    roleTitle: 'Engineer',
    status: 'Active',
    approved: 'Kim',
    createdDate: '02/03/23',
    lastLogin: '2024-04-01 8:49',
  },
  {
    id: '8',
    name: 'Will Stone',
    email: 'will.stone@company.com',
    roleTitle: 'sales',
    status: 'pending',
    approved: 'Jen',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 8:49',
  },
  {
    id: '9',
    name: 'David Shiela',
    email: 'david.shiela@company.com',
    roleTitle: 'Business Analyst',
    status: 'pending',
    approved: 'Kim',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 6:39',
  },
  {
    id: '10',
    name: 'Eric Larissa',
    email: 'eric.larissa@company.com',
    roleTitle: 'Product Owner',
    status: 'pending',
    approved: 'Ken',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 6:39',
  },
  {
    id: '11',
    name: 'May Azan',
    email: 'may.azan@company.com',
    roleTitle: 'Developer',
    status: 'Active',
    approved: 'Kim',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 6:39',
  },
  {
    id: '12',
    name: 'Angel Michael',
    email: 'angel.michael@company.com',
    roleTitle: 'Data',
    status: 'Active',
    approved: 'Jen',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 6:39',
  },
  {
    id: '13',
    name: 'Ed Long',
    email: 'ed.long@company.com',
    roleTitle: 'Data',
    status: 'Active',
    approved: 'Ken',
    createdDate: '02/01/23',
    lastLogin: '2/18/2024 14:39',
  },

  {
    id: '	14	',
    name: '	Lucas Johnson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/18/2024	',
    lastLogin: '	2/18/24 14:39',
  },
  {
    id: '	15	',
    name: '	Liam Wright	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/18/2024	',
    lastLogin: '	2/18/24 14:39',
  },
  {
    id: '	16	',
    name: '	 Jasper Rivera	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/19/2024	',
    lastLogin: '	2/19/24 12:00',
  },
  {
    id: '	17	',
    name: '	John Long	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/20/2024	',
    lastLogin: '	2/20/24 12:45',
  },
  {
    id: '	18	',
    name: '	 Jasper Walker 	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/21/2024	',
    lastLogin: '	2/21/24 12:45',
  },
  {
    id: '	19	',
    name: '	Jasper Thompson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/22/2024	',
    lastLogin: '	2/22/24 12:00',
  },
  {
    id: '	20	',
    name: '	Laura Swift	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/23/2024	',
    lastLogin: '	2/23/24 12:45',
  },
  {
    id: '	21	',
    name: '	 Lucas Rivera 	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/24/2024	',
    lastLogin: '	2/24/24 12:00',
  },
  {
    id: '	22	',
    name: '	Ethan Kim	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/25/2024	',
    lastLogin: '	2/25/24 12:00',
  },
  {
    id: '	23	',
    name: '	Mario Silverio	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/26/2024	',
    lastLogin: '	2/26/24 12:00',
  },
  {
    id: '	24	',
    name: '	Aurora Wright	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/27/2024	',
    lastLogin: '	2/27/24 14:39',
  },
  {
    id: '	25	',
    name: '	Jasper Rivera	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	2/28/2024	',
    lastLogin: '	2/28/24 12:45',
  },
  {
    id: '	26	',
    name: '	Camila Bennett	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	2/29/2024	',
    lastLogin: '	2/29/24 12:45',
  },
  {
    id: '	27	',
    name: '	Liam Torres	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/1/2024	',
    lastLogin: '	3/1/24 15:49',
  },
  {
    id: '	28	',
    name: '	Evelyn Patel	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/2/2024	',
    lastLogin: '	3/2/24 14:39',
  },
  {
    id: '	29	',
    name: '	Noah Miller	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/3/2024	',
    lastLogin: '	3/3/24 14:39',
  },
  {
    id: '	30	',
    name: '	Riley Jackson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/4/2024	',
    lastLogin: '	3/4/24 15:49',
  },
  {
    id: '	31	',
    name: '	Penelope Hernandez	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/5/2024	',
    lastLogin: '	3/5/24 15:49',
  },
  {
    id: '	32	',
    name: '	Mason Lee	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/6/2024	',
    lastLogin: '	3/6/24 12:00',
  },
  {
    id: '	33	',
    name: '	Audrey Young	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/7/2024	',
    lastLogin: '	3/7/24 12:00',
  },
  {
    id: '	34	',
    name: '	Ethan Garcia	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/8/2024	',
    lastLogin: '	3/8/24 15:49',
  },
  {
    id: '	35	',
    name: '	Scarlett Walker	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/9/2024	',
    lastLogin: '	3/9/24 15:49',
  },
  {
    id: '	36	',
    name: '	Lucas Thompson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/10/2024	',
    lastLogin: '	3/10/24 12:00',
  },
  {
    id: '	37	',
    name: '	Charlotte Allen	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/11/2024	',
    lastLogin: '	3/11/24 12:00',
  },
  {
    id: '	38	',
    name: '	Benjamin Kim	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/12/2024	',
    lastLogin: '	3/12/24 12:00',
  },
  {
    id: '	39	',
    name: '	Amelia Gonzalez	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/13/2024	',
    lastLogin: '	3/13/24 12:00',
  },
  {
    id: '	40	',
    name: '	Michael Johnson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/14/2024	',
    lastLogin: '	3/14/24 12:00',
  },
  {
    id: '	41	',
    name: '	Harper Davis	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/15/2024	',
    lastLogin: '	3/15/24 12:00',
  },
  {
    id: '	42	',
    name: '	Elijah Moore	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/16/2024	',
    lastLogin: '	3/16/24 12:00',
  },
  {
    id: '	43	',
    name: '	Ava Robinson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/17/2024	',
    lastLogin: '	3/17/24 12:00',
  },
  {
    id: '	44	',
    name: '	Audrey Young	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/18/2024	',
    lastLogin: '	3/18/24 12:00',
  },
  {
    id: '	45	',
    name: '	Ethan Garcia	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/19/2024	',
    lastLogin: '	3/19/24 15:49',
  },
  {
    id: '	46	',
    name: '	Scarlett Walker	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/20/2024	',
    lastLogin: '	3/20/24 12:00',
  },
  {
    id: '	47	',
    name: '	Lucas Thompson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/21/2024	',
    lastLogin: '	3/21/24 12:00',
  },
  {
    id: '	48	',
    name: '	Benjamin Kim	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/22/2024	',
    lastLogin: '	3/22/24 12:00',
  },
  {
    id: '	49	',
    name: '	Amelia Gonzalez	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/23/2024	',
    lastLogin: '	3/23/24 15:49',
  },
  {
    id: '	50	',
    name: '	Michael A. Johnson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Pending	',
    approved: '	Kim 	',
    createdDate: '	3/24/2024	',
    lastLogin: '	3/24/24 12:00',
  },
  {
    id: '51',
    name: 'Ed Long',
    email: 'ed.long@company.com',
    roleTitle: 'Data',
    status: 'Active',
    approved: 'Ken',
    createdDate: '2024-02-17',
    lastLogin: '2024-03-19 14:39',
  },

  {
    id: '	52	',
    name: '	Lucas Johnson	',
    email: '	name@90days.com	',
    roleTitle: 'Data',
    status: '	Active	',
    approved: '	Kim 	',
    createdDate: '	2/18/2024	',
    lastLogin: '	2/18/24 14:39',
  },
] as unknown as User[]

export const RECORDS_PER_PAGE = 50
