import Link from 'next/link';
import ArrowCards from './components/cards/ArrowCards';
import ProgramCards from './components/cards/ProgramCards';
import StatCards from './components/cards/StatCards';
import HeaderCarousel from './components/header/HeaderCarousel';

function HomePage() {
  return <>
    <HeaderCarousel />
    <>
      <section>
        <ArrowCards />
      </section>

      <section className='bg-primary-lighter padding-2'>
        <div className='margin-bottom-3'>
          <h2 className='margin-top-0 margin-bottom-1 text-size-2xl'>Small Businesses Are Vital to the U.S. Economy</h2>
          <p>Small businesses play a crucial role in the U.S. economy. In 2023, $170.3 Billion was generated by small businesses. The federal government seeks your collaboration!</p>
        </div>
        <StatCards />
        <img className='width-full margin-top-2' src='/images/homepage-infographic.jpg' alt='Infographic on US Small Businesses' />
      </section>

      <section className='bg-white padding-2'>
        <h2 className='margin-top-0 margin-bottom-1 text-size-2xl'>Benefits of Certification</h2>

        <ul className='padding-left-2 line-height-base'>
          <li style={{display: 'list-item'}}>Access to sole-source and competitive set-aside contracts</li>
          <li style={{display: 'list-item'}}>Assistance from federal procurement experts</li>
          <li style={{display: 'list-item'}}>Business development assistance from dedicated Business Opportunity Specialists</li>
          <li style={{display: 'list-item'}}>Opportunities to create joint ventures with established businesses</li>
          <li style={{display: 'list-item'}}>Priority access to federal surplus property</li>
        </ul>
      </section>

      <section className='bg-primary-lighter padding-2'>
        <div className='margin-bottom-1'>
          <h2 className='margin-top-0 margin-bottom-1 text-size-2xl'>Our Programs</h2>
          <p>SBA offers six certifications, and eight total programs, to help you stand out, find contracts, and grow your business.</p>
        </div>
        <ProgramCards />
      </section>

      <section style={{backgroundColor: '#002E6D'}} className='display-flex flex-justify-center flex-column flex-align-center padding-4'>
        <h2 className='margin-top-0 margin-bottom-4 text-center text-size-2xl text-white line-height-base'>
					Stand out from the crowd.<br />
					Get Certified!
        </h2>

        <div>
          <Link className="usa-button" style={{backgroundColor: '#D83933'}} href={'/login'} >
              Create Account
          </Link>
        </div>
      </section>
    </>
  </>;
}
export default HomePage
