import { IBusinessProfile } from './types';

export const businessProfileData: Record<string, IBusinessProfile> = {
  '1234567890ab': {
    id: 1,
    sam_entity: {
      sam_entity_id: 1,
      dba_name: 'Buck Enterprises',
      legal_business_name: 'Uncle Buck\'s Organic Coffee',
      uei: '01234567890ab',
      physical_address_1: '123 Sesame Street',
      physical_address_2: 'Apt 65',
      physical_city: 'Manhattan',
      mailing_address_state_or_province: 'NY',
      physical_zip_code_5: '81231',
      govt_bus_poc_first_name: 'Elon',
      govt_bus_poc_last_name: 'Musk',
      entity_structure: 'S Corporation',
      cage_code: '',
      account_hash: '',
      tax_identifier_number: '',
      sam_extract_code: '',
      claimed: false
    },
    owner_user_id: 1,
    type: 'business',
    structure: 'S Corporation',
    deleted_at: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    owner_user: 1,
  },
  '1234567890cd': {
    id: 2,
    sam_entity: {
      sam_entity_id: 2,
      dba_name: 'Buck Enterprises',
      legal_business_name: 'Uncle Buck\'s Flowershop',
      uei: '01234567890cd',
      physical_address_1: '345 Sesame Street',
      physical_address_2: '',
      physical_city: 'Manhattan',
      mailing_address_state_or_province: 'NY',
      physical_zip_code_5: '81231',
      govt_bus_poc_first_name: 'Clark',
      govt_bus_poc_last_name: 'Kent',
      entity_structure: 'S Corporation',
      cage_code: '',
      account_hash: '',
      tax_identifier_number: '',
      sam_extract_code: '',
      claimed: false
    },
    owner_user_id: 2,
    type: 'business',
    structure: 'S Corporation',
    deleted_at: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    owner_user: 2,
  },
  '1234567890ef': {
    id: 3,
    sam_entity: {
      sam_entity_id: 3,
      dba_name: 'Buck Enterprises',
      legal_business_name: 'Uncle Buck\'s Barbershop',
      uei: '01234567890ef',
      physical_address_1: '567 Sesame Street',
      physical_address_2: '',
      physical_city: 'Manhattan',
      mailing_address_state_or_province: 'NY',
      physical_zip_code_5: '81231',
      govt_bus_poc_first_name: 'Donald',
      govt_bus_poc_last_name: 'Trump',
      entity_structure: 'S Corporation',
      cage_code: '',
      account_hash: '',
      tax_identifier_number: '',
      sam_extract_code: '',
      claimed: false
    },
    owner_user_id: 3,
    type: 'business',
    structure: 'S Corporation',
    deleted_at: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    owner_user: 3,
  },
  '1234567890gh': {
    id: 4,
    sam_entity: {
      sam_entity_id: 4,
      dba_name: 'Buck Enterprises',
      legal_business_name: 'Uncle Buck\'s Candy Shop',
      uei: '01234567890gh',
      physical_address_1: '789 Sesame Street',
      physical_address_2: '',
      physical_city: 'Manhattan',
      mailing_address_state_or_province: 'NY',
      physical_zip_code_5: '81231',
      govt_bus_poc_first_name: 'Ryan',
      govt_bus_poc_last_name: 'Renolds',
      entity_structure: 'S Corporation',
      cage_code: '',
      account_hash: '',
      tax_identifier_number: '',
      sam_extract_code: '',
      claimed: false
    },
    owner_user_id: 4,
    type: 'business',
    structure: 'S Corporation',
    deleted_at: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    owner_user: 4,
  }
}
