export const tooltipCmbInvite = 'Invitation Codes - Shared with Contributor or Delegate to begin application process.\n For more information, quick references, and FAQs, click here (Knowledge Base)'

export const toolTipCmbInvitationInfo = `The Unified Certification Process (UCP) Landing Page provides you the opportunity to learn more about the Small Business Administration (SBA), available certification programs, and create an account.
Before creating an account, please note that you must register your business on http://sam.gov/. To learn more about registering your business, please go to https://sam.gov/content/entity-registration.To create an account, please enter your email and a secure password. You will receive an email to verify your account and complete the account creation process.\n\n Unsure which certification programs you qualify for? Please use our “Should I Apply?” pre-eligibility assessment tool to learn more about qualifications and applicant requirements. For certification program requirements including required documentation, please navigate to the “Documentation” hyperlink located at the bottom of the page.\n\nSystem for Award Management (SAM)/SAM.gov - Applicants are required to register in the System for Award Management (SAM). Each applicant may go to http://sam.gov/  (https://www.sam.gov)/ and answer the appropriate SAM questions found in the Representations and Certifications section, FAR 52.212-3, and Small Business Program Representations section, FAR 52.219-1.\n\n For more information, quick references, and FAQs, click here (Knowledge Base).`

export const toolTipCmbInputs = {
  'uei': 'Unique Entity ID (UEI) - The Unique Entity ID is a 12-character alphanumeric ID assigned to an entity by SAM.gov | Home .',
  'cageCode': 'Commercial and Government Entity (CAGE) Code - The CAGE Code is a five character ID number used by the Federal Government to identify vendors.',
  'tin': 'A Taxpayer Identification Number (TIN) is an identification number used by the Internal Revenue Service (IRS) in the administration of tax laws. This could be a Social Security Number (SSN), Employer Identification Number (EIN), Individual Taxpayer Identification Number (ITIN), or other TIN. This number should be the TIN associated to your SAM.gov | Home registration.',
  'bankAccountNumber': '',
  'serverError': ''
}

export const toolTipCmbValidation = 'Claiming your business allows you to claim your initial business and/or additional businesses. Once you claim a business, the business details will then be found on your "Business Profile" in UCP. You will not be able to make edits to your business details in UCP, you must make any necessary changes in http://sam.gov/. If you make any updates to your business details in http://sam.gov/, the turn-around time for UCP to be updated with the new information is approximately 3 business days after the changes have been ACTIVATED in http://sam.gov/ .'
