export const arrowCardData = [
  {
    title: 'Should I Apply?',
    img: '/images/should-i-apply.jpg',
    text: 'See if the time is right for your business',
    class: 'arrow-box-one',
    link: '/should-i-apply/ownership'
  },
  {
    title: 'Prepare for Application',
    img: '/images/prepare.jpg',
    text: 'Get your business ready for certification',
    class: 'arrow-box-two',
    link: '/resources/get-ready'
  },
  {
    title: 'Create An Account',
    img: '/images/create-account.jpg',
    text: 'Start your certification experience',
    class: 'arrow-box-three',
    link: '/login'
  },
]

export const informationCardData = [
  {
    statNumber: '27%',
    statDetail: 'of all Federal Contracts are',
  },
  {
    statNumber: '$170.3 B',
    statDetail: 'in 2023 was generated by',
  },
  {
    statNumber: '33.2 M',
    statDetail: 'of all US businesses are',
  }
]

export const programCardData = [
  {
    subTitle: '8(a)',
    title: '8(a) Business Development',
    link: 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/8a-business-development-program',
  },
  {
    subTitle: 'HUBZone',
    title: 'HUBZone',
    link: 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/hubzone-program',
  },
  {
    subTitle: 'VOSB',
    title: 'Veteran-Owned',
    link: 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/veteran-contracting-assistance-programs',
  },
  {
    subTitle: 'WOSB',
    title: 'Women-Owned',
    link: 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/women-owned-small-business-federal-contract-program',
  },
  {
    subTitle: 'Entity-Owned',
    title: 'Entity-Owned',
    link: '/login',
  },
]
