export const arrowCardData = [
  {
    title: 'Should I Apply?',
    img: '/images/should-i-apply.jpg',
    text: 'See if your business qualifies for certification',
    class: 'arrow-box-one'
  },
  {
    title: 'Prepare for Application',
    img: '/images/prepare.jpg',
    text: 'Get your business ready for certification',
    class: 'arrow-box-two'
  },
  {
    title: 'Create An Account',
    img: '/images/create-account.jpg',
    text: 'Start your certification experience',
    class: 'arrow-box-three'
  },
]

export const informationCardData = [
  {
    statNumber: '27%',
    statDetail: 'of all Federal Contracts are',
  },
  {
    statNumber: '$170.3 B',
    statDetail: 'in 2023 was generated by',
  },
  {
    statNumber: '33.2 M',
    statDetail: 'of all US businesses are',
  }
]

export const programCardData = [
  {
    subTitle: '8(a)',
    title: '8(a) Business Development'
  },
  {
    subTitle: 'HUBZone',
    title: 'HUBZone'
  },
  {
    subTitle: 'VOSB',
    title: 'Veteran-Owned'
  },
  {
    subTitle: 'WOSB',
    title: 'Women-Owned'
  },
  {
    subTitle: 'MPP',
    title: 'Mentor-Protégé Program'
  },
  {
    subTitle: 'Entity-Owned',
    title: 'Entity-Owned'
  },
]
