export enum Role {
  EXTERNAL = 'external_user',
  PRIMARY_QUALIFYING_OWNER = 'primary_qualifying_owner',
  CONTRIBUTOR = 'contributor',
  DELEGATE = 'delegate',
  SPOUSE = 'spouse',
  ADMIN = 'ucms_admin',
  INTERNAL = 'internal_user',
  SCREENER = 'screener',
  SCREENER_COMMON_APP = 'SCREENER_COMMON_APP',
  ANALYST = 'analyst',
  ANALYST_HIGH_TIER = 'analyst_high_criteria',
  ANALYST_LOW_TIER = 'analyst_low_criteria',
  REVIEWER = 'supervisor',
  REVIEWER_HIGH_TIER = 'supervisor_high_criteria',
  REVIEWER_LOW_TIER = 'supervisor_low_criteria',
  APPROVER_8a_aabd = 'approver_8a_aabd',
  ANALYST_CONTRIBUTOR_OGC = 'analyst_contributor_ogc',
  ANALYST_CONTRIBUTOR_OSS = 'analyst_contributor_oss'
}