//Empty object if prod data is unavailable
export const entities = [
  // {
  //   id: 1,
  //   sam_entity: {
  //     sam_entity_id: 4,
  //     legal_business_name: 'Becker-Harris',
  //     uei: '057OR6L0BT3T',
  //     cage_code: '4I3X3',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'becker-harris',
  //     physical_address_1: '321 Mckee Throughway',
  //     physical_address_2: 'Suite 600',
  //     physical_city: 'Smithville',
  //     mailing_address_state_or_province: 'Utah',
  //     physical_zip_code_5: '58217',
  //     sam_extract_code: '2',
  //     entity_structure: 'CY',
  //     govt_bus_poc_first_name: 'Amanda',
  //     govt_bus_poc_last_name: 'Hernandez',
  //   },
  //   owner_user_id: 8,
  //   type: 'holding company',
  //   structure: 'corp',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.093811Z',
  //   updated_at: '2024-05-08T16:51:26.093824Z',
  // },
  // {
  //   id: 2,
  //   sam_entity: {
  //     sam_entity_id: 17,
  //     legal_business_name: 'Parker Group',
  //     uei: 'EJN4EXOUMK3H',
  //     cage_code: 'Z6NYF',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'parker group',
  //     physical_address_1: '748 Shaw Circle',
  //     physical_address_2: 'Suite 060',
  //     physical_city: 'South Jacquelinestad',
  //     mailing_address_state_or_province: 'Maine',
  //     physical_zip_code_5: '31614',
  //     sam_extract_code: '3',
  //     entity_structure: 'ZZ',
  //     govt_bus_poc_first_name: 'Heidi',
  //     govt_bus_poc_last_name: 'York',
  //   },
  //   owner_user_id: 7,
  //   type: 'branch',
  //   structure: 'corp',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.108810Z',
  //   updated_at: '2024-05-08T16:51:26.108817Z',
  // },
  // {
  //   id: 3,
  //   sam_entity: {
  //     sam_entity_id: 2,
  //     legal_business_name: 'Young, Pierce and Maxwell',
  //     uei: 'WOKS13I4798E',
  //     cage_code: 'S9TT1',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'young, pierce and maxwell',
  //     physical_address_1: '05959 Oconnor Ville',
  //     physical_address_2: 'Suite 531',
  //     physical_city: 'Codyshire',
  //     mailing_address_state_or_province: 'Idaho',
  //     physical_zip_code_5: '49873',
  //     sam_extract_code: '4',
  //     entity_structure: '2J',
  //     govt_bus_poc_first_name: 'Joseph',
  //     govt_bus_poc_last_name: 'Oconnor',
  //   },
  //   owner_user_id: 2,
  //   type: 'holding company',
  //   structure: 'corp',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.116988Z',
  //   updated_at: '2024-05-08T16:51:26.116996Z',
  // },
  // {
  //   id: 4,
  //   sam_entity: {
  //     sam_entity_id: 15,
  //     legal_business_name: 'Estrada-Moore',
  //     uei: 'UDP36U7K17GM',
  //     cage_code: 'XIU6V',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'estrada-moore',
  //     physical_address_1: '878 Hernandez Via',
  //     physical_address_2: 'Suite 101',
  //     physical_city: 'Jacobstad',
  //     mailing_address_state_or_province: 'Alaska',
  //     physical_zip_code_5: '54221',
  //     sam_extract_code: '1',
  //     entity_structure: '2L',
  //     govt_bus_poc_first_name: 'Kevin',
  //     govt_bus_poc_last_name: 'Vega',
  //   },
  //   owner_user_id: 8,
  //   type: 'branch',
  //   structure: 'llc',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.125022Z',
  //   updated_at: '2024-05-08T16:51:26.125029Z',
  // },
  // {
  //   id: 5,
  //   sam_entity: {
  //     sam_entity_id: 6,
  //     legal_business_name: 'Jones-Cohen',
  //     uei: 'DNFBH2BBE7F5',
  //     cage_code: '6ODTC',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'jones-cohen',
  //     physical_address_1: '60222 Nolan Turnpike',
  //     physical_address_2: 'Suite 948',
  //     physical_city: 'Grantstad',
  //     mailing_address_state_or_province: 'Oregon',
  //     physical_zip_code_5: '73658',
  //     sam_extract_code: 'A',
  //     entity_structure: '2A',
  //     govt_bus_poc_first_name: 'Shelby',
  //     govt_bus_poc_last_name: 'Mahoney',
  //   },
  //   owner_user_id: 2,
  //   type: 'holding company',
  //   structure: 'corp',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.133621Z',
  //   updated_at: '2024-05-08T16:51:26.133628Z',
  // },
  // {
  //   id: 6,
  //   sam_entity: {
  //     sam_entity_id: 3,
  //     legal_business_name: 'Harrison, Lopez and Berry',
  //     uei: 'N0AJSZK8C4N6',
  //     cage_code: 'Y8L8D',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'harrison, lopez and berry',
  //     physical_address_1: '970 Stafford Tunnel',
  //     physical_address_2: 'Suite 495',
  //     physical_city: 'East Jessicaport',
  //     mailing_address_state_or_province: 'Pennsylvania',
  //     physical_zip_code_5: '82380',
  //     sam_extract_code: 'E',
  //     entity_structure: '2J',
  //     govt_bus_poc_first_name: 'Jared',
  //     govt_bus_poc_last_name: 'Castaneda',
  //   },
  //   owner_user_id: 4,
  //   type: 'subsidiary',
  //   structure: 'llc',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.142872Z',
  //   updated_at: '2024-05-08T16:51:26.142880Z',
  // },
  // {
  //   id: 7,
  //   sam_entity: {
  //     sam_entity_id: 13,
  //     legal_business_name: 'Mckinney, Harrison and Hays',
  //     uei: 'QZ0N8E62XPD0',
  //     cage_code: '41VDI',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'mckinney, harrison and hays',
  //     physical_address_1: '3623 Gregory Lights',
  //     physical_address_2: 'Suite 643',
  //     physical_city: 'Martinezhaven',
  //     mailing_address_state_or_province: 'Louisiana',
  //     physical_zip_code_5: '26219',
  //     sam_extract_code: '4',
  //     entity_structure: '2J',
  //     govt_bus_poc_first_name: 'David',
  //     govt_bus_poc_last_name: 'Miller',
  //   },
  //   owner_user_id: 3,
  //   type: 'holding company',
  //   structure: 'partnership',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.153318Z',
  //   updated_at: '2024-05-08T16:51:26.153326Z',
  // },
  // {
  //   id: 8,
  //   sam_entity: {
  //     sam_entity_id: 14,
  //     legal_business_name: 'Williams and Sons',
  //     uei: '5VM5MSMPOI68',
  //     cage_code: 'UP39D',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'williams and sons',
  //     physical_address_1: '217 Michelle Expressway',
  //     physical_address_2: 'Suite 009',
  //     physical_city: 'Randallburgh',
  //     mailing_address_state_or_province: 'Maryland',
  //     physical_zip_code_5: '84377',
  //     sam_extract_code: '3',
  //     entity_structure: '2L',
  //     govt_bus_poc_first_name: 'Noah',
  //     govt_bus_poc_last_name: 'Marshall',
  //   },
  //   owner_user_id: 10,
  //   type: 'subsidiary',
  //   structure: 'partnership',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.161364Z',
  //   updated_at: '2024-05-08T16:51:26.161370Z',
  // },
  // {
  //   id: 9,
  //   sam_entity: {
  //     sam_entity_id: 10,
  //     legal_business_name: 'Flores, Choi and Mcmillan',
  //     uei: '2H63ECS2J0Z5',
  //     cage_code: 'K2TRI',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'flores, choi and mcmillan',
  //     physical_address_1: '325 Tony Fords',
  //     physical_address_2: 'Suite 887',
  //     physical_city: 'Lanetown',
  //     mailing_address_state_or_province: 'West Virginia',
  //     physical_zip_code_5: '32421',
  //     sam_extract_code: 'E',
  //     entity_structure: 'X6',
  //     govt_bus_poc_first_name: 'Kara',
  //     govt_bus_poc_last_name: 'Keller',
  //   },
  //   owner_user_id: 1,
  //   type: 'holding company',
  //   structure: 'partnership',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.169678Z',
  //   updated_at: '2024-05-08T16:51:26.169684Z',
  // },
  // {
  //   id: 10,
  //   sam_entity: {
  //     sam_entity_id: 8,
  //     legal_business_name: 'Garcia PLC',
  //     uei: 'P9MLN3YJ5FDX',
  //     cage_code: '4UYPO',
  //     account_hash: '123456789',
  //     tax_identifier_number: '123456789',
  //     dba_name: 'garcia plc',
  //     physical_address_1: '244 Shawna Turnpike',
  //     physical_address_2: 'Suite 020',
  //     physical_city: 'West Seanfurt',
  //     mailing_address_state_or_province: 'Tennessee',
  //     physical_zip_code_5: '39372',
  //     sam_extract_code: '3',
  //     entity_structure: '8H',
  //     govt_bus_poc_first_name: 'Alexandra',
  //     govt_bus_poc_last_name: 'Cruz',
  //   },
  //   owner_user_id: 6,
  //   type: 'holding company',
  //   structure: 'partnership',
  //   deleted_at: null,
  //   created_at: '2024-05-08T16:51:26.177587Z',
  //   updated_at: '2024-05-08T16:51:26.177594Z',
  // },
]
